spring:
  profiles:
    active:
    - dev

---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            
    driver-class-name: org.gjt.mm.mysql.Driver             
    url: jdbc:mysql://106.12.24.76:3306/cloudDB01              
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                          
      initial-size: 5                                       
      max-total: 5                                         
      max-wait-millis: 200                                  

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        
  type-aliases-package: com.test.springcloud.entities       
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                     


eureka:
  client: 
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true


---
server:
  port: 8001

spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            
    driver-class-name: org.gjt.mm.mysql.Driver             
    url: jdbc:mysql://106.12.24.76:3306/cloudDB02              
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           
      initial-size: 5                                      
      max-total: 5                                         
      max-wait-millis: 200                                  

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml       
  type-aliases-package: com.test.springcloud.entities     
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                 


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true